add/movingbase
KBKN-Autonomous-Robotics-Lab/tsukuba2023-src pull request #5
Opened 2023-09-13 13:40 UTC by kengohozumi

・概要
movingbaseの方位情報を使用できるようにする。
imuは低速や180°回転させたとき方位情報が不安定になってします。

・詳細
movingbase_node.pyの追加

movingbaseの方位情報をimuの方位情報の代わりに自己位置推定で使えるようにします。
今後movingbaseの方位情報が使える箇所があったらそこにも追加します。

その他
方位情報を他で使えるところがありましたら教えていただきたいです。
今後、movingbaseは絶対方位を推定することができるのでそのメリットを活用したいです。

2023-09-13 16:30 UTC, koki0624 reviewed
ドラフトになっていましたが、review request がきたので気になったことをコメントしておきます。

2023-09-13 16:30 UTC, koki0624 commented on tsukuba2023/scripts/movingbase_node.py
1. Pythonによるノードの書き方を検討し直してみてください。
https://pystyle.info/ros-create-publisher-and-subscriber-with-rospy/
書き方はいろいろですが、上記のサイトにあるように main メソッドを作ったりするとプログラムの流れや構造的にも分かりやすいかなと思います。

2. あまり人のことを言えないのですが、全体を通してプログラムのフォーマットが一貫してないので、もう少し統一してもらえると読みやすくなります。
（=や&, << などの演算子や、"," などの前後にスペースがあったり無かったり2つあったり）
（ifの後ろにスペースがあったりなかったり）
フォーマッターを使ってみてもいいかもしれません。

2023-09-13 16:30 UTC, koki0624 commented on tsukuba2023/scripts/movingbase_node.py
> +def readPosned():
関数名がちょっとわかりにくいかもです。

2023-09-13 16:30 UTC, koki0624 commented on tsukuba2023/scripts/movingbase_node.py
> +    with serial.Serial('/dev/sensors/GNSSrover', 19200, timeout=1) as ser:
デバイス名はパラメータにしましょう。

2023-09-13 16:30 UTC, koki0624 commented on tsukuba2023/scripts/movingbase_node.py
> +        CK_B = CK_B +CK_A
フォーマットについて、例えばこんな感じです。
43行目の +6 も意味があるなら変数の方がいいです。

```suggestion
def checksum(ackPacket, payloadlength):
    CK_A = 0
    CK_B = 0
    for i in range(2, payloadlength+6):
        CK_A = CK_A + int.from_bytes(ackPacket[i], byteorder='little', signed=False) 
        CK_B = CK_B + CK_A
```

2023-09-13 16:30 UTC, koki0624 commented on tsukuba2023/scripts/movingbase_node.py
> +    pub = rospy.Publisher('/movingbase_yaw', Imu, queue_size=10)
この関数内に rospy.initi_node() や rospy.Publisher() があると、ループの中で何度も実行されています。本来は一度でいい処理なので、見直しましょう。

2023-09-13 16:30 UTC, koki0624 commented on tsukuba2023/scripts/movingbase_node.py
> +        while i < payloadlength+8:
+8 に意味があるなら変数にした方がいいかと思います。

2023-09-13 17:23 UTC, Alpaca-zip reviewed
@koki0624 も指摘してくれていますが、私からも、ぱっと見た感じでの気になった点&アドバイスを書いておきます。

- 以下のような簡単なスクリプトの例を参考にしながら、コーディングをしてみると見た目も美しく、可読性の比較的高いものが出来上がると思うので参考にしてみてください。
http://wiki.ros.org/ja/ROS/Tutorials/WritingPublisherSubscriber%28python%29

- スクリプトを書くときはフォーマッタを併用しましょう。なんでも良いと思いますが個人的にはBlackがおすすめです。参考程度ですが、インストール方法とフォーマットの掛け方を示しておきます。

  **install**
  ```
  $ pip install black
  ```
  **Format with Black**
  ```
  $ find . -type f -name "*.py" -exec black {} \;
  ```

2023-09-13 17:23 UTC, Alpaca-zip commented on tsukuba2023/scripts/movingbase_node.py
> +import serial
`#!/usr/bin/env python3`のようなshebang(シバン)の記述
ROSでは`./movingbase_node.py`のような形でPythonのスクリプトを実行することはないので基本的には必要ないですが、本来は"書かなければいけないもの"です。書くクセをつけておくと良いと思います。

2023-09-13 17:23 UTC, Alpaca-zip commented on tsukuba2023/scripts/movingbase_node.py
> +while 1:
- `if __name__ == "__main__": `の記述
これもshebang同様に無くても動作はしますが、慣習として書いておいた方が良いものです。スクリプトを読む側も、「ここから読めばいいんだ」と一目で分かります。また、main メソッドを使って明示的にエントリーポイントを指定することについてですが、ROSの公式ドキュメントの例では使っていないので、そこは好みでよいと思います。

- `while 1:`について
`while not rospy.is_shutdown():`という行はCtrl+cでROSノードを停止するとwhile文を抜けるというものですが、それをさらに`while 1:`で無限ループするというのは、機能として意味を持ちません。
`while 1:`を使う正しい場面であったとしてもbreak文と併用することを忘れないようにしましょう。

2023-09-13 23:04 UTC, kengohozumi commented
添削ありがとうございます
一度imuとmovingbaseのバグをとって値を比較したかったので出しました。
そのあとプログラムの中身を整理しようと思います。

2023-10-24 04:35 UTC, Alpaca-zip commented
ドラフト解除をされたようですが、レビューして欲しいということでしょうか。
レビューして欲しい場合には、レビューのRerequestをしてください。

2023-10-24 06:42 UTC, kengohozumi commented
もう一度検証して確認できたらRerequestします　その時よろしくお願いします

2023-10-25 11:25 UTC, Alpaca-zip reviewed
レビューする前に単純な疑問なのですが、[movingbase_node.py](https://github.com/KBKN-Autonomous-Robotics-Lab/tsukuba2023-src/blob/4aadc4e2dba60a35c44b260b19ecfbaf9e1df176/tsukuba2023/scripts/movingbase_node.py)と[movingbase_node_v1.py](https://github.com/KBKN-Autonomous-Robotics-Lab/tsukuba2023-src/blob/4aadc4e2dba60a35c44b260b19ecfbaf9e1df176/tsukuba2023/scripts/movingbase_node_v1.py)に分ける理由って何かあるんですか？

2023-10-25 12:03 UTC, kengohozumi commented
すみません
movingbase_node.pyを消し忘れていました

2023-10-25 12:47 UTC, Alpaca-zip commented
> すみません movingbase_node.pyを消し忘れていました

movingbase_node_v1.pyの内容をmovingbase_node.pyにコピーして、movingbase_node_v1.pyは削除する形で良いと思います。

2023-10-25 13:59 UTC, kengohozumi commented
今日動作の確認が終わりました。

2023-10-26 04:04 UTC, Alpaca-zip requested changes
- コメントアウトで`print()`を使っている箇所は`rospy.logdebug()`を利用するようにしてください。
- コード内にちらほらquoという言葉を見かけますがこれはquaternionのことですか？であればquoではなくquaが正しいと思います。一般的にはquatと表現されることが多いのでこちらで統一する方が良いと思います。
- 基本的に命名規則が統一されていません。movingbase_node.pyは良いと思いますが、この命名規則に合わせるのであれば、movingbase_to_quat.pyとかの方が分かりやすいと思います。

2023-10-26 04:04 UTC, Alpaca-zip commented on tsukuba2023/scripts/movingbasetoquo.py
> +#!/usr/bin/env python
```suggestion
#!/usr/bin/env python3
```

2023-10-26 04:04 UTC, Alpaca-zip commented on tsukuba2023/scripts/movingbasetoquo.py
> +        movingbasequo.movingbase_publish_msg()
```suggestion
if  __name__ == "__main__":
    # init node
    rospy.init_node("movingbase")
    movingbasequo = movingbaseNode()
    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        movingbasequo.movingbase_publish_msg()
        rate.sleep()
```

2023-10-26 04:04 UTC, Alpaca-zip commented on tsukuba2023/scripts/movingbasetoquo.py
> +        rate = rospy.Rate(10)
```suggestion
```

2023-10-26 06:51 UTC, Alpaca-zip approved these changes

2023-10-26 06:51 UTC, merged