feature/convert gps to odom
KBKN-Autonomous-Robotics-Lab/tsukuba2023-src pull request #7
Opened 2023-10-18 12:13 UTC by kengohozumi

・概要
GPSをodomに変換してナビゲーションに活用できるようにします。

・詳細
GPSodom.pyの追加
self.theta とself.initial_coordinateを使用する場所によって変更してください。
self.thetaはロボットの初期方位
self.initial_coordinateはロボットが初期位置(緯度経度)

2023-10-19 06:40 UTC, Alpaca-zip requested changes
手元で動作の確認をする方法がないので中身のみのレビューになります。
___
お願いした箇所の修正が終わったら以下で、コードフォーマットしてもらえると嬉しいです。
```bash
black GPSodom.py
```

2023-10-19 06:40 UTC, Alpaca-zip commented on tsukuba2023/launch/sensors.launch
> +    <node name="GPSodom"   pkg="tsukuba2023" type="GPSodom.py" />
```suggestion
    <node name="GPSodom" pkg="tsukuba2023" type="GPSodom.py" />
```

2023-10-19 06:40 UTC, Alpaca-zip commented on tsukuba2023/scripts/GPSodom.py
> +        self.initial_coordinate = [35.709918, 139.523032]#[latitude,longitude] nakaniwa 35.709918, 139.523032 tsukuba 36.082868166666664, 140.07699316666665
`self.theta`と`self.initial_coordinate`はROSのパラメータにした方が良いと思います。

2023-10-19 06:40 UTC, Alpaca-zip commented on tsukuba2023/scripts/GPSodom.py
> +        #print(y)
```suggestion
        rospy.logdebug("y: %f", y)
```

2023-10-19 06:40 UTC, Alpaca-zip commented on tsukuba2023/scripts/GPSodom.py
> +        #print(x)
```suggestion
        rospy.logdebug("x: %f", x)
```

2023-10-19 06:40 UTC, Alpaca-zip commented on tsukuba2023/scripts/GPSodom.py
> +            #print(self.latlon_info)
```suggestion
            rospy.logdebug("GPSxy: (%f, %f)", GPSxy[0], GPSxy[1])
            rospy.logdebug("LatLon info: %s", str(self.latlon_info))
```

2023-10-19 06:40 UTC, Alpaca-zip commented on tsukuba2023/scripts/GPSodom.py
> +        #rospy.spin()
```suggestion
        rospy.spinOnce()
```

2023-10-19 06:40 UTC, Alpaca-zip commented on tsukuba2023/scripts/GPSodom.py
> +    while not rospy.is_shutdown():
`Rate(10)`(10Hz)とかで良いのでsleepするようにしてください。

2023-10-19 06:40 UTC, Alpaca-zip commented on tsukuba2023/scripts/GPSodom.py
> +        #gtodom.print_fix()
デバッグするのにソースコードを編集するのはあまり良くないので、パラメータなどで`print_fix()`を実行するかを選択できると良いと思います。

2023-10-21 13:11 UTC, kengohozumi commented on tsukuba2023/scripts/GPSodom.py
> +        #rospy.spin()
rospy.spin()を加えるとtopicが出力されなくなり
rospy.spinOnce()を加えると
Traceback (most recent call last):
  File "GPSodom.py", line 177, in <module>
    rospy.spinOnce()
AttributeError: module 'rospy' has no attribute 'spinOnce'
のようなエラーが出るのですが、、、

2023-10-21 13:18 UTC, Alpaca-zip commented on tsukuba2023/scripts/GPSodom.py
> +        #rospy.spin()
失礼しました。pythonにはspinOnce()は必要ないみたいです。
この指摘は無視してください。

2023-10-21 13:20 UTC, kengohozumi commented on tsukuba2023/scripts/GPSodom.py
> +        #rospy.spin()
分かりました
ありがとうございます

2023-10-24 08:10 UTC, Alpaca-zip reviewed
以前指摘した箇所の修正含め、このPR内容の作業がすべて終了したらRerequestしてください。

2023-10-26 04:22 UTC, Alpaca-zip requested changes
`# calculation below`などはそのままで良いですが、`# rospy.logdebug("x: %f", x)`などについてはコメントアウトを外すか削除してしまってください。

2023-10-26 04:22 UTC, Alpaca-zip commented on tsukuba2023/launch/sensors.launch
> +    <node name="GPSodom"   pkg="tsukuba2023" type="GPSodom.py">
以前指摘したところですが以下修正お願いします。
```suggestion
    <node name="GPSodom"  pkg="tsukuba2023" type="GPSodom.py">
```

2023-10-26 06:17 UTC, Alpaca-zip approved these changes
問題無いと思います。

2023-10-26 06:19 UTC, Alpaca-zip reviewed
tsukuba2023/launch/sensors.launchでconflictを起こしているのでそこだけ修正してください。

2023-10-26 06:36 UTC, merged